"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import Header from "@/components/Header";
import { Box, ClientOnly, Skeleton } from "@chakra-ui/react";
import { useColorModeValue } from "../components/ui/color-mode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {/* nu zit useColorModeValue binnen de Chakra context */}
          <AppLayout>{children}</AppLayout>
        </Provider>
      </body>
    </html>
  );
}

function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClientOnly fallback={<Skeleton minH="100vh" />}>
      <AppLayoutContent>{children}</AppLayoutContent>
    </ClientOnly>
  );
}

function AppLayoutContent({ children }: { children: React.ReactNode }) {
  const bg = useColorModeValue("#F1E7DB", "#202022");
  return (
    <Box minH="100vh" bg={bg}>
      <Header path="" />
      {children}
    </Box>
  );
}
